name: gitsprint
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # boardview: ^0.2.2
  boardview:
    #path: ../../../FlutterBoardView
    git:
      url: git://github.com/ianmaciel/FlutterBoardView.git
      ref: feature/drag-and-drop-on-click
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  gitlab:
    path: ../../../gitlab-dart
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
    # git:
    #   url: git://github.com/ianmaciel/FlutterBoardView.git
    #   ref: feature/drag-and-drop-on-click

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
